services:
  - type: web
    name: lumos-api
    runtime: docker
    repo: https://github.com/WebAppLumos/lumos-api
    branch: main
    dockerfilePath: ./Dockerfile
    plan: free
    region: singapore
    healthCheckPath: /health
    autoDeployTrigger: commit
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: CORS_ALLOWED_ORIGIN_PATTERNS
        sync: false
