spring.application.name=lumos-api

# 테스트 용도라 DB 접속정보를 하드코딩합니다.
spring.datasource.url=jdbc:postgresql://ep-autumn-mouse-ao51pabx-pooler.c-2.ap-southeast-1.aws.neon.tech/lumos_db?sslmode=require&channelBinding=require
spring.datasource.username=lumos
spring.datasource.password=npg_owC70iYXpsWA
spring.datasource.driver-class-name=org.postgresql.Driver

# Flyway가 동일한 DataSource를 사용하도록 기본 활성화 상태를 명시합니다.
spring.flyway.enabled=true
