spring.application.name=lumos-api

# PostgreSQL 연결 (하드코딩)
spring.datasource.url=jdbc:postgresql://ep-autumn-mouse-ao51pabx-pooler.c-2.ap-southeast-1.aws.neon.tech/lumos_db?sslmode=require&channel_binding=require
spring.datasource.username=lumos
spring.datasource.password=npg_owC70iYXpsWA
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Flyway (마이그레이션 사용 시 폴더 설정)
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
