CREATE TABLE places (
    place_id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    name VARCHAR(255) NOT NULL,
    building VARCHAR(255),
    type VARCHAR(100),
    time VARCHAR(100),

    lat DOUBLE PRECISION,
    lng DOUBLE PRECISION,

    CONSTRAINT pk_places PRIMARY KEY (place_id)
);