-- Lumos API 초기 스키마 (JPA 엔티티 기준)
-- 기존 Hibernate ddl-auto 가 만든 테이블을 정리하고 깨끗하게 재생성한다.

DROP TABLE IF EXISTS entries CASCADE;
DROP TABLE IF EXISTS notes CASCADE;
DROP TABLE IF EXISTS timetables CASCADE;
DROP TABLE IF EXISTS courses CASCADE;
DROP TABLE IF EXISTS semesters CASCADE;
DROP TABLE IF EXISTS calendar CASCADE;
DROP TABLE IF EXISTS previous_semester_scores CASCADE;
DROP TABLE IF EXISTS language_exams CASCADE;
DROP TABLE IF EXISTS certifications CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- 사용자
CREATE TABLE users (
    user_id           VARCHAR(255) NOT NULL,
    email             VARCHAR(255) NOT NULL,
    name              VARCHAR(100) NOT NULL,
    phone_number      VARCHAR(30)  NOT NULL,
    major             VARCHAR(100) NOT NULL,
    grade             INTEGER      NOT NULL,
    student_number    VARCHAR(7)   NOT NULL,
    profile_image_url TEXT,
    created_at        TIMESTAMP    NOT NULL,
    updated_at        TIMESTAMP    NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (user_id),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT uk_users_phone_number UNIQUE (phone_number),
    CONSTRAINT uk_users_student_number UNIQUE (student_number)
);

-- 학사/개인 일정
CREATE TABLE calendar (
    schedule_id  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id      VARCHAR(255),
    title        VARCHAR(100),
    content      TEXT,
    date         DATE,
    is_completed BOOLEAN,
    category     VARCHAR(30),
    priority     VARCHAR(10),
    created_at   TIMESTAMP,
    updated_at   TIMESTAMP,
    CONSTRAINT pk_calendar PRIMARY KEY (schedule_id),
    CONSTRAINT fk_calendar_user FOREIGN KEY (user_id) REFERENCES users (user_id)
);

-- 학기
CREATE TABLE semesters (
    semester_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id     VARCHAR(255) NOT NULL,
    title       VARCHAR(100) NOT NULL,
    start_date  DATE         NOT NULL,
    end_date    DATE         NOT NULL,
    is_active   BOOLEAN      NOT NULL,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP,
    CONSTRAINT pk_semesters PRIMARY KEY (semester_id),
    CONSTRAINT fk_semesters_user FOREIGN KEY (user_id) REFERENCES users (user_id)
);

-- 과목
CREATE TABLE courses (
    course_id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    semester_id      BIGINT       NOT NULL,
    title            VARCHAR(100) NOT NULL,
    course_code      VARCHAR(8),
    professor        VARCHAR(50),
    classroom        VARCHAR(50),
    credit           SMALLINT,
    difficulty_level SMALLINT,
    created_at       TIMESTAMP,
    updated_at       TIMESTAMP,
    CONSTRAINT pk_courses PRIMARY KEY (course_id),
    CONSTRAINT fk_courses_semester FOREIGN KEY (semester_id) REFERENCES semesters (semester_id)
);

-- 시간표
CREATE TABLE timetables (
    timetable_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    semester_id  BIGINT NOT NULL,
    title        VARCHAR(100),
    created_at   TIMESTAMP,
    updated_at   TIMESTAMP,
    CONSTRAINT pk_timetables PRIMARY KEY (timetable_id),
    CONSTRAINT fk_timetables_semester FOREIGN KEY (semester_id) REFERENCES semesters (semester_id)
);

-- 시간표 항목
CREATE TABLE entries (
    entry_id     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    timetable_id BIGINT NOT NULL,
    course_id    BIGINT NOT NULL,
    day_of_week  SMALLINT,
    start_time   TIME,
    end_time     TIME,
    created_at   TIMESTAMP,
    updated_at   TIMESTAMP,
    CONSTRAINT pk_entries PRIMARY KEY (entry_id),
    CONSTRAINT fk_entries_timetable FOREIGN KEY (timetable_id) REFERENCES timetables (timetable_id),
    CONSTRAINT fk_entries_course FOREIGN KEY (course_id) REFERENCES courses (course_id)
);

-- 강의 노트
CREATE TABLE notes (
    note_id    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    course_id  BIGINT NOT NULL,
    title      VARCHAR(100),
    content    TEXT,
    is_pinned  BOOLEAN,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT pk_notes PRIMARY KEY (note_id),
    CONSTRAINT fk_notes_course FOREIGN KEY (course_id) REFERENCES courses (course_id)
);

-- 이전 학기 성적
CREATE TABLE previous_semester_scores (
    grade_id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id    VARCHAR(255),
    score      DOUBLE PRECISION,
    year       DATE,
    semester   VARCHAR(10),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT pk_previous_semester_scores PRIMARY KEY (grade_id),
    CONSTRAINT fk_previous_semester_scores_user FOREIGN KEY (user_id) REFERENCES users (user_id)
);

-- 어학 시험
CREATE TABLE language_exams (
    exam_id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    exam_category VARCHAR(255),
    score         VARCHAR(255),
    exam_date     DATE,
    year          INTEGER,
    semester      VARCHAR(255),
    expiry_date   DATE,
    user_id       VARCHAR(255),
    CONSTRAINT pk_language_exams PRIMARY KEY (exam_id),
    CONSTRAINT fk_language_exams_user FOREIGN KEY (user_id) REFERENCES users (user_id)
);

-- 자격증
CREATE TABLE certifications (
    cert_id    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    cert_name  VARCHAR(255),
    issue_date DATE,
    user_id    VARCHAR(255),
    CONSTRAINT pk_certifications PRIMARY KEY (cert_id),
    CONSTRAINT fk_certifications_user FOREIGN KEY (user_id) REFERENCES users (user_id)
);
