-- 과제
CREATE TABLE assignments (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    course       VARCHAR(255) NOT NULL,
    title        VARCHAR(255) NOT NULL,
    deadline     VARCHAR(255) NOT NULL,
    is_completed BOOLEAN      NOT NULL,
    CONSTRAINT pk_assignments PRIMARY KEY (id)
);
