CREATE TABLE semester_grades (
    semester_grade_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id           VARCHAR(255)  NOT NULL,
    academic_year     INTEGER       NOT NULL,
    term_code         VARCHAR(2)    NOT NULL,
    term_name         VARCHAR(20)   NOT NULL,
    completed_credits INTEGER       NOT NULL DEFAULT 0,
    registered_credits INTEGER      NOT NULL DEFAULT 0,
    gpa               DOUBLE PRECISION NOT NULL DEFAULT 0,
    academic_warning  BOOLEAN       NOT NULL DEFAULT FALSE,
    synced_at         TIMESTAMP     NOT NULL,
    created_at        TIMESTAMP     NOT NULL,
    updated_at        TIMESTAMP     NOT NULL,
    CONSTRAINT pk_semester_grades PRIMARY KEY (semester_grade_id),
    CONSTRAINT fk_semester_grades_user FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT uq_semester_grades_user_term UNIQUE (user_id, academic_year, term_code)
);
